name: CI-CD

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
      DEV_DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
      DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Subir serviços com Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
          docker-compose -f docker-compose.yml ps

      - name: Esperar serviços ficarem disponíveis
        run: sleep 30

      - name: Executar testes
        run:  gradle test

      - name: Derrubar serviços do Docker Compose
        run: docker-compose -f docker-compose.yml down
